modLoader="javafml"
loaderVersion="[37,)"
license="GNU"
issueTrackerURL="https://github.com/SeriousandProGamers/Armageddon/issues"

[[mods]]
modId="armageddon"
version="${file.jarVersion}"
displayName="Armageddon"
updateJSONURL="https://raw.githubusercontent.com/SeriousandProGamers/Armageddon/main/update.json"
# displayURL="https://www.curseforge.com/minecraft/mc-mods/armageddon"
# logoFile="logo.png"
# credits=""
authors="ApexModder"
description='''
Adds the Zombie variants to the game with different abilities.
'''

[[dependencies.armageddon]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.armageddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18]"
    ordering="NONE"
    side="BOTH"